<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function isExist(array $options, $id): bool
    {
        $em = $this->getEntityManager();
        $categoryByName = $em->getRepository('AppBundle:Category')->findOneBy($options);
        if ($categoryByName->getId() != $id) {
            return false;
        }
        return true;
    }
}
