<?php

namespace AppBundle\Repository;

/**
 * ForgotPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForgotPasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
