<?php
/**
 * Created by PhpStorm.
 * User: Home-User
 * Date: 09.06.2017
 * Time: 14:51
 */

namespace AppBundle\Repository;

/**
 * ForgotPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForgotPasswordRepository extends \Doctrine\ORM\EntityRepository
{

}